#Erstelle eine Funktion `solve_maze_01()` welche mit Hilfe der Befehle `move(), turn_left(), turn_right()` die Charakterfigur zum Schatz bewegt. rufe diese funktion dann aus der Funktion `solve_maze()` auf und starte das programm

def solve_maze_1():
    move()
    move()
    move()
    turn_right()
    move()
    move()
    move()
    move()
    move()
    move()
    turn_right()
    move()
    turn_left()
    move()
    move()
    move()
    move()
    turn_left()
    move()
    move()
    turn_right()
    move()
    move()
    move()
    move()
    turn_right()
    move()
    move()
    move()
    move()
    turn_right()
    move()
    move()
    move()
    move()